// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.gm;

import javax.annotation.Generated;

@Generated("java_bean")
public enum GMErrorCode implements io.protostuff.EnumLite<GMErrorCode>
{
    GMErrorCode_Success(1),
    GMErrorCode_Param_Error(2),
    GMErrorCode_ParsePacket_Error(3),
    GMErrorCode_DbExec_Error(4),
    GMErrorCode_PlayerNotExists_Error(5),
    GMErrorCode_MemNotEnough_Error(6),
    GMErrorCode_Deposit_Item_Error(7),
    GMErrorCode_Deposit_Success(8),
    GMErrorCode_Mail_Success(9),
    GMErrorCode_Shop_Goods_Error(10),
    GMErrorCode_Shop_Success(11),
    GMErrorCode_Activity_Error(12),
    GMErrorCode_Activity_Task_Error(13),
    GMErrorCode_Activity_Success(14);
    
    public final int number;
    
    private GMErrorCode (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static GMErrorCode valueOf(int number)
    {
        switch(number) 
        {
            case 1: return GMErrorCode_Success;
            case 2: return GMErrorCode_Param_Error;
            case 3: return GMErrorCode_ParsePacket_Error;
            case 4: return GMErrorCode_DbExec_Error;
            case 5: return GMErrorCode_PlayerNotExists_Error;
            case 6: return GMErrorCode_MemNotEnough_Error;
            case 7: return GMErrorCode_Deposit_Item_Error;
            case 8: return GMErrorCode_Deposit_Success;
            case 9: return GMErrorCode_Mail_Success;
            case 10: return GMErrorCode_Shop_Goods_Error;
            case 11: return GMErrorCode_Shop_Success;
            case 12: return GMErrorCode_Activity_Error;
            case 13: return GMErrorCode_Activity_Task_Error;
            case 14: return GMErrorCode_Activity_Success;
            default: return null;
        }
    }
}
