// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.gm;

import javax.annotation.Generated;

@Generated("java_bean")
public enum GmMsgParam implements io.protostuff.EnumLite<GmMsgParam>
{
    enum_PlayerLoadReq_AccountId(0),
    enum_PlayerLoadReq_ServerId(1),
    enum_PlayerLoadRes_Res(2),
    enum_PlayerBlockReq_AccountId(256),
    enum_PlayerBlockReq_ServerId(257),
    enum_PlayerBlockReq_BlockSecond(258),
    enum_PlayerBlockReq_BlockRes(259),
    enum_PlayerBlockRes_Res(260),
    enum_PlayerBaseInfo_GetReq_AccountId(512),
    enum_PlayerBaseInfo_GetReq_ServerId(513),
    enum_PlayerBaseInfo_GetRes_AccountId(514),
    enum_PlayerBaseInfo_GetRes_ServerId(515),
    enum_PlayerBaseInfo_GetRes_Name(516),
    enum_PlayerBaseInfo_GetRes_Lv(517),
    enum_PlayerBaseInfo_GetRes_Exp(518),
    enum_PlayerBaseInfo_GetRes_UnionServerId(519),
    enum_PlayerBaseInfo_GetRes_UnionIndex(520),
    enum_PlayerBaseInfo_GetRes_UnionName(521),
    enum_PlayerBaseInfo_GetRes_UnionContribution(528),
    enum_PlayerBaseInfo_GetRes_HeroCount(529),
    enum_PlayerBaseInfo_GetRes_FrientCurrCount(530),
    enum_PlayerBaseInfo_GetRes_FrientMaxCount(531),
    enum_PlayerBaseInfo_GetRes_Gold(532),
    enum_PlayerBaseInfo_GetRes_Rmb(533),
    enum_PlayerBaseInfo_GetRes_PVECoin(534),
    enum_PlayerBaseInfo_GetRes_PVPCoin(535),
    enum_PlayerBaseInfo_GetRes_Decompose(536),
    enum_PlayerBaseInfo_GetRes_HuntingLv(537),
    enum_PlayerBaseInfo_GetRes_HuntingTest(544),
    enum_PlayerBaseInfo_GetRes_HuntingStrength(545),
    enum_PlayerBaseInfo_GetRes_TalentPoint(546),
    enum_PlayerBaseInfo_GetRes_MatchGrade(547),
    enum_PlayerBaseInfo_GetRes_MatchPoint(548),
    enum_PlayerBaseInfo_GetRes_Online(549),
    enum_PlayerBaseInfo_GetRes_BlockTime(550),
    enum_PlayerBaseInfo_GetRes_BlockSecond(551),
    enum_PlayerBaseInfo_GetRes_BlockRes(552),
    enum_PlayerBaseInfo_UpdateReq_AccountId(768),
    enum_PlayerBaseInfo_UpdateReq_ServerId(769),
    enum_PlayerBaseInfo_UpdateReq_Lv(770),
    enum_PlayerBaseInfo_UpdateReq_Exp(771),
    enum_PlayerBaseInfo_UpdateReq_Gold(772),
    enum_PlayerBaseInfo_UpdateReq_Rmb(773),
    enum_PlayerBaseInfo_UpdateReq_PVECoin(774),
    enum_PlayerBaseInfo_UpdateReq_PVPCoin(775),
    enum_PlayerBaseInfo_UpdateReq_Decompose(776),
    enum_PlayerBaseInfo_UpdateReq_HuntingTest(777),
    enum_PlayerBaseInfo_UpdateReq_HuntingStrength(784),
    enum_PlayerBaseInfo_UpdateReq_TalentPoint(785),
    enum_PlayerBaseInfo_UpdateReq_MatchPoint(786),
    enum_PlayerBaseInfo_UpdateRes(787),
    enum_Player_GetItem_res_ItemId(920),
    enum_Player_GetItem_res_ItemCount(921),
    enum_Player_updateItemReq_ItemId(1024),
    enum_Player_updateItemReq_ItemCount(1025),
    enum_player_GetHeroCount_ret(1280),
    enum_player_GetHero_res_Lv(1536),
    enum_player_GetHero_res_Exp(1537),
    enum_player_GetHero_res_Quality(1538),
    enum_player_GetHero_res_name(1539),
    enum_player_GetHero_res_Id(1540),
    enum_player_GetHero_res_skillCount(1541),
    enum_player_GetHero_res_skillId(1542),
    enum_player_GetHero_res_EquipCount(1552),
    enum_player_GetHero_res_EquipId(1553),
    enum_player_updateHero_req_HeroId(1568),
    enum_player_updateHero_req_Exp(1570),
    enum_player_updateHero_req_Quality(1571),
    enum_player_updateHero_req_SkilliD(1572),
    enum_player_updateHero_req_SkillIndex(1573),
    enum_player_GetMailCount_res(1616),
    enum_player_GetMail_res_MailId(1617),
    enum_player_GetMail_res_title(1618),
    enum_player_GetMail_res_GetTime(1619),
    enum_player_GetMail_res_accessoryCount(1620),
    enum_player_GetMail_res_accessoryItemId(1621),
    enum_player_GetMail_res_accessoryItemCount(1623),
    enum_player_GetMail_res_accessoryIsGet(1632),
    enum_player_updateMail_req_deleteMailId(1648),
    enum_player_GetRune_res_Count(2048),
    enum_player_GetRune_res_Id(2049),
    enum_player_GetRune_res_Type(2050),
    enum_player_GetRune_res_lv(2052),
    enum_player_UpdateRune_req_lv(2081),
    enum_player_GetFriend_res_Count(2128),
    enum_player_GetFriend_res_name(2129),
    enum_player_GetFriend_res_ID(2130),
    enum_player_GetFriend_res_lv(2131),
    enum_player_GetFriend_res_isOnline(2132),
    enum_player_UpdateFriend_req_delete_friendID(2144),
    enum_Server_GetPlayerCount(2304);
    
    public final int number;
    
    private GmMsgParam (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static GmMsgParam valueOf(int number)
    {
        switch(number) 
        {
            case 0: return enum_PlayerLoadReq_AccountId;
            case 1: return enum_PlayerLoadReq_ServerId;
            case 2: return enum_PlayerLoadRes_Res;
            case 256: return enum_PlayerBlockReq_AccountId;
            case 257: return enum_PlayerBlockReq_ServerId;
            case 258: return enum_PlayerBlockReq_BlockSecond;
            case 259: return enum_PlayerBlockReq_BlockRes;
            case 260: return enum_PlayerBlockRes_Res;
            case 512: return enum_PlayerBaseInfo_GetReq_AccountId;
            case 513: return enum_PlayerBaseInfo_GetReq_ServerId;
            case 514: return enum_PlayerBaseInfo_GetRes_AccountId;
            case 515: return enum_PlayerBaseInfo_GetRes_ServerId;
            case 516: return enum_PlayerBaseInfo_GetRes_Name;
            case 517: return enum_PlayerBaseInfo_GetRes_Lv;
            case 518: return enum_PlayerBaseInfo_GetRes_Exp;
            case 519: return enum_PlayerBaseInfo_GetRes_UnionServerId;
            case 520: return enum_PlayerBaseInfo_GetRes_UnionIndex;
            case 521: return enum_PlayerBaseInfo_GetRes_UnionName;
            case 528: return enum_PlayerBaseInfo_GetRes_UnionContribution;
            case 529: return enum_PlayerBaseInfo_GetRes_HeroCount;
            case 530: return enum_PlayerBaseInfo_GetRes_FrientCurrCount;
            case 531: return enum_PlayerBaseInfo_GetRes_FrientMaxCount;
            case 532: return enum_PlayerBaseInfo_GetRes_Gold;
            case 533: return enum_PlayerBaseInfo_GetRes_Rmb;
            case 534: return enum_PlayerBaseInfo_GetRes_PVECoin;
            case 535: return enum_PlayerBaseInfo_GetRes_PVPCoin;
            case 536: return enum_PlayerBaseInfo_GetRes_Decompose;
            case 537: return enum_PlayerBaseInfo_GetRes_HuntingLv;
            case 544: return enum_PlayerBaseInfo_GetRes_HuntingTest;
            case 545: return enum_PlayerBaseInfo_GetRes_HuntingStrength;
            case 546: return enum_PlayerBaseInfo_GetRes_TalentPoint;
            case 547: return enum_PlayerBaseInfo_GetRes_MatchGrade;
            case 548: return enum_PlayerBaseInfo_GetRes_MatchPoint;
            case 549: return enum_PlayerBaseInfo_GetRes_Online;
            case 550: return enum_PlayerBaseInfo_GetRes_BlockTime;
            case 551: return enum_PlayerBaseInfo_GetRes_BlockSecond;
            case 552: return enum_PlayerBaseInfo_GetRes_BlockRes;
            case 768: return enum_PlayerBaseInfo_UpdateReq_AccountId;
            case 769: return enum_PlayerBaseInfo_UpdateReq_ServerId;
            case 770: return enum_PlayerBaseInfo_UpdateReq_Lv;
            case 771: return enum_PlayerBaseInfo_UpdateReq_Exp;
            case 772: return enum_PlayerBaseInfo_UpdateReq_Gold;
            case 773: return enum_PlayerBaseInfo_UpdateReq_Rmb;
            case 774: return enum_PlayerBaseInfo_UpdateReq_PVECoin;
            case 775: return enum_PlayerBaseInfo_UpdateReq_PVPCoin;
            case 776: return enum_PlayerBaseInfo_UpdateReq_Decompose;
            case 777: return enum_PlayerBaseInfo_UpdateReq_HuntingTest;
            case 784: return enum_PlayerBaseInfo_UpdateReq_HuntingStrength;
            case 785: return enum_PlayerBaseInfo_UpdateReq_TalentPoint;
            case 786: return enum_PlayerBaseInfo_UpdateReq_MatchPoint;
            case 787: return enum_PlayerBaseInfo_UpdateRes;
            case 920: return enum_Player_GetItem_res_ItemId;
            case 921: return enum_Player_GetItem_res_ItemCount;
            case 1024: return enum_Player_updateItemReq_ItemId;
            case 1025: return enum_Player_updateItemReq_ItemCount;
            case 1280: return enum_player_GetHeroCount_ret;
            case 1536: return enum_player_GetHero_res_Lv;
            case 1537: return enum_player_GetHero_res_Exp;
            case 1538: return enum_player_GetHero_res_Quality;
            case 1539: return enum_player_GetHero_res_name;
            case 1540: return enum_player_GetHero_res_Id;
            case 1541: return enum_player_GetHero_res_skillCount;
            case 1542: return enum_player_GetHero_res_skillId;
            case 1552: return enum_player_GetHero_res_EquipCount;
            case 1553: return enum_player_GetHero_res_EquipId;
            case 1568: return enum_player_updateHero_req_HeroId;
            case 1570: return enum_player_updateHero_req_Exp;
            case 1571: return enum_player_updateHero_req_Quality;
            case 1572: return enum_player_updateHero_req_SkilliD;
            case 1573: return enum_player_updateHero_req_SkillIndex;
            case 1616: return enum_player_GetMailCount_res;
            case 1617: return enum_player_GetMail_res_MailId;
            case 1618: return enum_player_GetMail_res_title;
            case 1619: return enum_player_GetMail_res_GetTime;
            case 1620: return enum_player_GetMail_res_accessoryCount;
            case 1621: return enum_player_GetMail_res_accessoryItemId;
            case 1623: return enum_player_GetMail_res_accessoryItemCount;
            case 1632: return enum_player_GetMail_res_accessoryIsGet;
            case 1648: return enum_player_updateMail_req_deleteMailId;
            case 2048: return enum_player_GetRune_res_Count;
            case 2049: return enum_player_GetRune_res_Id;
            case 2050: return enum_player_GetRune_res_Type;
            case 2052: return enum_player_GetRune_res_lv;
            case 2081: return enum_player_UpdateRune_req_lv;
            case 2128: return enum_player_GetFriend_res_Count;
            case 2129: return enum_player_GetFriend_res_name;
            case 2130: return enum_player_GetFriend_res_ID;
            case 2131: return enum_player_GetFriend_res_lv;
            case 2132: return enum_player_GetFriend_res_isOnline;
            case 2144: return enum_player_UpdateFriend_req_delete_friendID;
            case 2304: return enum_Server_GetPlayerCount;
            default: return null;
        }
    }
}
