// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.gm;

import javax.annotation.Generated;

@Generated("java_bean")
public enum GmMsgType implements io.protostuff.EnumLite<GmMsgType>
{
    enum_Msg_Gm2Logic_Player_Load_Req(48),
    enum_Msg_Logic2Gm_Player_Load_Res(49),
    enum_Msg_Gm2Logic_Player_Block_Req(50),
    enum_Msg_Logic2Gm_Player_Block_Res(51),
    enum_Msg_Gm2Logic_Player_BaseInfo_Get_Req(52),
    enum_Msg_Logic2Gm_Player_BaseInfo_Get_Res(53),
    enum_Msg_Gm2Logic_Player_BaseInfo_Update_Req(54),
    enum_Msg_Logic2Gm_Player_BaseInfo_Update_Res(55),
    enum_Msg_Gm2Logic_Player_HeroInfo_Get_Req(56),
    enum_Msg_Logic2Gm_Player_HeroInfo_Get_Res(57),
    enum_Msg_Gm2Logic_Player_HeroInfo_Update_Req(58),
    enum_Msg_Logic2Gm_Player_HeroInfo_Update_Res(59),
    enum_Msg_Gm2Logic_Player_ItemInfo_Get_Req(60),
    enum_Msg_Logic2Gm_Player_ItemInfo_Get_Res(61),
    enum_Msg_Gm2Logic_Player_ItemInfo_Update_Req(62),
    enum_Msg_Logic2Gm_Player_ItemInfo_Update_Res(63),
    enum_Msg_Gm2Logic_Player_MailInfo_Get_Req(64),
    enum_Msg_Logic2Gm_Player_MailInfo_Get_Res(65),
    enum_Msg_Gm2Logic_Player_MailInfo_Update_Req(66),
    enum_Msg_Logic2Gm_Player_MailInfo_Update_Res(67),
    enum_Msg_Gm2Logic_Player_RuneInfo_Get_Req(68),
    enum_Msg_Logic2Gm_Player_RuneInfo_Get_Res(69),
    enum_Msg_Gm2Logic_Player_RuneInfo_Update_Req(70),
    enum_Msg_Logic2Gm_Player_RuneInfo_Update_Res(71),
    enum_Msg_Gm2Logic_Player_TalentInfo_Get_Req(72),
    enum_Msg_Logic2Gm_Player_TalentInfo_Get_Res(73),
    enum_Msg_Gm2Logic_Player_TalentInfo_Update_Req(74),
    enum_Msg_Logic2Gm_Player_TalentInfo_Update_Res(75),
    enum_Msg_Gm2Logic_Player_FriendInfo_Get_Req(76),
    enum_Msg_Logic2Gm_Player_FriendInfo_Get_Res(77),
    enum_Msg_Gm2Logic_Player_FriendInfo_Update_Req(78),
    enum_Msg_Logic2Gm_Player_FriendInfo_Update_Res(79),
    enum_Msg_Gm2Logic_Player_Unblock_Req(80),
    enum_Msg_Logic2Gm_Player_Unblock_Res(81),
    enum_Msg_Gm2Logic_Player_Kicket_Req(82),
    enum_Msg_Logic2Gm_Player_Kicket_Res(83),
    enum_Msg_Gm2Logic_GetServerInfo_Req(112),
    enum_Msg_Logic2Gm_GetServerInfo_Res(113);
    
    public final int number;
    
    private GmMsgType (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static GmMsgType valueOf(int number)
    {
        switch(number) 
        {
            case 48: return enum_Msg_Gm2Logic_Player_Load_Req;
            case 49: return enum_Msg_Logic2Gm_Player_Load_Res;
            case 50: return enum_Msg_Gm2Logic_Player_Block_Req;
            case 51: return enum_Msg_Logic2Gm_Player_Block_Res;
            case 52: return enum_Msg_Gm2Logic_Player_BaseInfo_Get_Req;
            case 53: return enum_Msg_Logic2Gm_Player_BaseInfo_Get_Res;
            case 54: return enum_Msg_Gm2Logic_Player_BaseInfo_Update_Req;
            case 55: return enum_Msg_Logic2Gm_Player_BaseInfo_Update_Res;
            case 56: return enum_Msg_Gm2Logic_Player_HeroInfo_Get_Req;
            case 57: return enum_Msg_Logic2Gm_Player_HeroInfo_Get_Res;
            case 58: return enum_Msg_Gm2Logic_Player_HeroInfo_Update_Req;
            case 59: return enum_Msg_Logic2Gm_Player_HeroInfo_Update_Res;
            case 60: return enum_Msg_Gm2Logic_Player_ItemInfo_Get_Req;
            case 61: return enum_Msg_Logic2Gm_Player_ItemInfo_Get_Res;
            case 62: return enum_Msg_Gm2Logic_Player_ItemInfo_Update_Req;
            case 63: return enum_Msg_Logic2Gm_Player_ItemInfo_Update_Res;
            case 64: return enum_Msg_Gm2Logic_Player_MailInfo_Get_Req;
            case 65: return enum_Msg_Logic2Gm_Player_MailInfo_Get_Res;
            case 66: return enum_Msg_Gm2Logic_Player_MailInfo_Update_Req;
            case 67: return enum_Msg_Logic2Gm_Player_MailInfo_Update_Res;
            case 68: return enum_Msg_Gm2Logic_Player_RuneInfo_Get_Req;
            case 69: return enum_Msg_Logic2Gm_Player_RuneInfo_Get_Res;
            case 70: return enum_Msg_Gm2Logic_Player_RuneInfo_Update_Req;
            case 71: return enum_Msg_Logic2Gm_Player_RuneInfo_Update_Res;
            case 72: return enum_Msg_Gm2Logic_Player_TalentInfo_Get_Req;
            case 73: return enum_Msg_Logic2Gm_Player_TalentInfo_Get_Res;
            case 74: return enum_Msg_Gm2Logic_Player_TalentInfo_Update_Req;
            case 75: return enum_Msg_Logic2Gm_Player_TalentInfo_Update_Res;
            case 76: return enum_Msg_Gm2Logic_Player_FriendInfo_Get_Req;
            case 77: return enum_Msg_Logic2Gm_Player_FriendInfo_Get_Res;
            case 78: return enum_Msg_Gm2Logic_Player_FriendInfo_Update_Req;
            case 79: return enum_Msg_Logic2Gm_Player_FriendInfo_Update_Res;
            case 80: return enum_Msg_Gm2Logic_Player_Unblock_Req;
            case 81: return enum_Msg_Logic2Gm_Player_Unblock_Res;
            case 82: return enum_Msg_Gm2Logic_Player_Kicket_Req;
            case 83: return enum_Msg_Logic2Gm_Player_Kicket_Res;
            case 112: return enum_Msg_Gm2Logic_GetServerInfo_Req;
            case 113: return enum_Msg_Logic2Gm_GetServerInfo_Res;
            default: return null;
        }
    }
}
