// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.gm;

import javax.annotation.Generated;

@Generated("java_bean")
public enum GmRouteMsgType implements io.protostuff.EnumLite<GmRouteMsgType>
{
    GmRouteMsgType_Price_Update(1),
    GmRouteMsgType_Shelve_Update(2),
    GmRouteMsgType_OffShelve_Update(3),
    GmRouteMsgType_ToyCode(4),
    GmRouteMsgType_Activity_Update(5),
    GmRouteMsgType_Activity_Close(6),
    GmRouteMsgType_Activity_Delete(7);
    
    public final int number;
    
    private GmRouteMsgType (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static GmRouteMsgType valueOf(int number)
    {
        switch(number) 
        {
            case 1: return GmRouteMsgType_Price_Update;
            case 2: return GmRouteMsgType_Shelve_Update;
            case 3: return GmRouteMsgType_OffShelve_Update;
            case 4: return GmRouteMsgType_ToyCode;
            case 5: return GmRouteMsgType_Activity_Update;
            case 6: return GmRouteMsgType_Activity_Close;
            case 7: return GmRouteMsgType_Activity_Delete;
            default: return null;
        }
    }
}
