// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.gm;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.Objects;


@Generated("java_bean")
public final class Msg_Logic2Gm_GM_Res implements Externalizable, Message<Msg_Logic2Gm_GM_Res>, Schema<Msg_Logic2Gm_GM_Res>
{

    public static Schema<Msg_Logic2Gm_GM_Res> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static Msg_Logic2Gm_GM_Res getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final Msg_Logic2Gm_GM_Res DEFAULT_INSTANCE = new Msg_Logic2Gm_GM_Res();

    
    private String mSerialNumber;
    private Integer mType;
    private Integer mAccountId;
    private Integer mServerId;
    private GmKeyValueList mRetInfo;
    private Integer mRet;

    public Msg_Logic2Gm_GM_Res()
    {

    }

    // getters and setters

    // mSerialNumber

    public String getMSerialNumber()
    {
        return mSerialNumber;
    }


    public void setMSerialNumber(String mSerialNumber)
    {
        this.mSerialNumber = mSerialNumber;
    }

    // mType

    public Integer getMType()
    {
        return mType;
    }


    public void setMType(Integer mType)
    {
        this.mType = mType;
    }

    // mAccountId

    public Integer getMAccountId()
    {
        return mAccountId;
    }


    public void setMAccountId(Integer mAccountId)
    {
        this.mAccountId = mAccountId;
    }

    // mServerId

    public Integer getMServerId()
    {
        return mServerId;
    }


    public void setMServerId(Integer mServerId)
    {
        this.mServerId = mServerId;
    }

    // mRetInfo

    public GmKeyValueList getMRetInfo()
    {
        return mRetInfo;
    }


    public void setMRetInfo(GmKeyValueList mRetInfo)
    {
        this.mRetInfo = mRetInfo;
    }

    // mRet

    public Integer getMRet()
    {
        return mRet;
    }


    public void setMRet(Integer mRet)
    {
        this.mRet = mRet;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || this.getClass() != obj.getClass()) {
            return false;
        }
        final Msg_Logic2Gm_GM_Res that = (Msg_Logic2Gm_GM_Res) obj;
        return
                Objects.equals(this.mSerialNumber, that.mSerialNumber) &&
                Objects.equals(this.mType, that.mType) &&
                Objects.equals(this.mAccountId, that.mAccountId) &&
                Objects.equals(this.mServerId, that.mServerId) &&
                Objects.equals(this.mRetInfo, that.mRetInfo) &&
                Objects.equals(this.mRet, that.mRet);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mSerialNumber, mType, mAccountId, mServerId, mRetInfo, mRet);
    }

    @Override
    public String toString() {
        return "Msg_Logic2Gm_GM_Res{" +
                    "mSerialNumber=" + mSerialNumber +
                    ", mType=" + mType +
                    ", mAccountId=" + mAccountId +
                    ", mServerId=" + mServerId +
                    ", mRetInfo=" + mRetInfo +
                    ", mRet=" + mRet +
                '}';
    }
    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<Msg_Logic2Gm_GM_Res> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public Msg_Logic2Gm_GM_Res newMessage()
    {
        return new Msg_Logic2Gm_GM_Res();
    }

    public Class<Msg_Logic2Gm_GM_Res> typeClass()
    {
        return Msg_Logic2Gm_GM_Res.class;
    }

    public String messageName()
    {
        return Msg_Logic2Gm_GM_Res.class.getSimpleName();
    }

    public String messageFullName()
    {
        return Msg_Logic2Gm_GM_Res.class.getName();
    }

    public boolean isInitialized(Msg_Logic2Gm_GM_Res message)
    {
        return true;
    }

    public void mergeFrom(Input input, Msg_Logic2Gm_GM_Res message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.mSerialNumber = input.readString();
                    break;
                case 2:
                    message.mType = input.readUInt32();
                    break;
                case 3:
                    message.mAccountId = input.readUInt32();
                    break;
                case 4:
                    message.mServerId = input.readUInt32();
                    break;
                case 5:
                    message.mRetInfo = input.mergeObject(message.mRetInfo, GmKeyValueList.getSchema());
                    break;

                case 6:
                    message.mRet = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, Msg_Logic2Gm_GM_Res message) throws IOException
    {
        if(message.mSerialNumber != null)
            output.writeString(1, message.mSerialNumber, false);

        if(message.mType != null)
            output.writeUInt32(2, message.mType, false);

        if(message.mAccountId != null)
            output.writeUInt32(3, message.mAccountId, false);

        if(message.mServerId != null)
            output.writeUInt32(4, message.mServerId, false);

        if(message.mRetInfo != null)
             output.writeObject(5, message.mRetInfo, GmKeyValueList.getSchema(), false);


        if(message.mRet != null)
            output.writeUInt32(6, message.mRet, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    

}
