// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.gm;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;
import io.protostuff.UninitializedMessageException;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@Generated("java_bean")
public final class Msg_Gm2Logic_Route_Req implements Externalizable, Message<Msg_Gm2Logic_Route_Req>, Schema<Msg_Gm2Logic_Route_Req>
{

    public static Schema<Msg_Gm2Logic_Route_Req> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static Msg_Gm2Logic_Route_Req getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final Msg_Gm2Logic_Route_Req DEFAULT_INSTANCE = new Msg_Gm2Logic_Route_Req();

    
    private String mSerialNumber;
    private Integer mAccountId;
    private Integer mServerId;
    private Integer mType;
    private List<Long> mParm;
    private List<String> mParmStr;

    public Msg_Gm2Logic_Route_Req()
    {

    }

    public Msg_Gm2Logic_Route_Req(
        String mSerialNumber,
        Integer mAccountId,
        Integer mServerId,
        Integer mType
    )
    {
        this.mSerialNumber = mSerialNumber;
        this.mAccountId = mAccountId;
        this.mServerId = mServerId;
        this.mType = mType;
    }

    // getters and setters

    // mSerialNumber

    public String getMSerialNumber()
    {
        return mSerialNumber;
    }


    public void setMSerialNumber(String mSerialNumber)
    {
        this.mSerialNumber = mSerialNumber;
    }

    // mAccountId

    public Integer getMAccountId()
    {
        return mAccountId;
    }


    public void setMAccountId(Integer mAccountId)
    {
        this.mAccountId = mAccountId;
    }

    // mServerId

    public Integer getMServerId()
    {
        return mServerId;
    }


    public void setMServerId(Integer mServerId)
    {
        this.mServerId = mServerId;
    }

    // mType

    public Integer getMType()
    {
        return mType;
    }


    public void setMType(Integer mType)
    {
        this.mType = mType;
    }

    // mParm

    public List<Long> getMParmList()
    {
        return mParm;
    }


    public void setMParmList(List<Long> mParm)
    {
        this.mParm = mParm;
    }

    // mParmStr

    public List<String> getMParmStrList()
    {
        return mParmStr;
    }


    public void setMParmStrList(List<String> mParmStr)
    {
        this.mParmStr = mParmStr;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || this.getClass() != obj.getClass()) {
            return false;
        }
        final Msg_Gm2Logic_Route_Req that = (Msg_Gm2Logic_Route_Req) obj;
        return
                Objects.equals(this.mSerialNumber, that.mSerialNumber) &&
                Objects.equals(this.mAccountId, that.mAccountId) &&
                Objects.equals(this.mServerId, that.mServerId) &&
                Objects.equals(this.mType, that.mType) &&
                Objects.equals(this.mParm, that.mParm) &&
                Objects.equals(this.mParmStr, that.mParmStr);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mSerialNumber, mAccountId, mServerId, mType, mParm, mParmStr);
    }

    @Override
    public String toString() {
        return "Msg_Gm2Logic_Route_Req{" +
                    "mSerialNumber=" + mSerialNumber +
                    ", mAccountId=" + mAccountId +
                    ", mServerId=" + mServerId +
                    ", mType=" + mType +
                    ", mParm=" + mParm +
                    ", mParmStr=" + mParmStr +
                '}';
    }
    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<Msg_Gm2Logic_Route_Req> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public Msg_Gm2Logic_Route_Req newMessage()
    {
        return new Msg_Gm2Logic_Route_Req();
    }

    public Class<Msg_Gm2Logic_Route_Req> typeClass()
    {
        return Msg_Gm2Logic_Route_Req.class;
    }

    public String messageName()
    {
        return Msg_Gm2Logic_Route_Req.class.getSimpleName();
    }

    public String messageFullName()
    {
        return Msg_Gm2Logic_Route_Req.class.getName();
    }

    public boolean isInitialized(Msg_Gm2Logic_Route_Req message)
    {
        return 
            message.mSerialNumber != null 
            && message.mAccountId != null 
            && message.mServerId != null 
            && message.mType != null;
    }

    public void mergeFrom(Input input, Msg_Gm2Logic_Route_Req message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.mSerialNumber = input.readString();
                    break;
                case 2:
                    message.mAccountId = input.readUInt32();
                    break;
                case 3:
                    message.mServerId = input.readUInt32();
                    break;
                case 4:
                    message.mType = input.readUInt32();
                    break;
                case 5:
                    if(message.mParm == null)
                        message.mParm = new ArrayList<Long>();
                    message.mParm.add(input.readUInt64());break;
                case 6:
                    if(message.mParmStr == null)
                        message.mParmStr = new ArrayList<String>();
                    message.mParmStr.add(input.readString());break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, Msg_Gm2Logic_Route_Req message) throws IOException
    {
        if(message.mSerialNumber == null)
            throw new UninitializedMessageException(message);
        output.writeString(1, message.mSerialNumber, false);

        if(message.mAccountId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(2, message.mAccountId, false);

        if(message.mServerId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(3, message.mServerId, false);

        if(message.mType == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(4, message.mType, false);

        if(message.mParm != null)
        {
            for(Long mParm : message.mParm)
            {
                if(mParm != null)
                    output.writeUInt64(5, mParm, true);
            }
        }

        if(message.mParmStr != null)
        {
            for(String mParmStr : message.mParmStr)
            {
                if(mParmStr != null)
                    output.writeString(6, mParmStr, true);
            }
        }
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    

}
