// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.gm;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;
import io.protostuff.UninitializedMessageException;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.Objects;

@Generated("java_bean")
public final class Msg_Gm2Logic_Activity_Finsh_Req implements Externalizable, Message<Msg_Gm2Logic_Activity_Finsh_Req>, Schema<Msg_Gm2Logic_Activity_Finsh_Req>
{

    public static Schema<Msg_Gm2Logic_Activity_Finsh_Req> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static Msg_Gm2Logic_Activity_Finsh_Req getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final Msg_Gm2Logic_Activity_Finsh_Req DEFAULT_INSTANCE = new Msg_Gm2Logic_Activity_Finsh_Req();

    
    private String mSerialNumber;
    private Integer mAccountId;
    private Integer mServerId;
    private Integer mActivityId;
    private Integer mTaskId;

    public Msg_Gm2Logic_Activity_Finsh_Req()
    {

    }

    public Msg_Gm2Logic_Activity_Finsh_Req(
        String mSerialNumber,
        Integer mAccountId,
        Integer mServerId,
        Integer mActivityId,
        Integer mTaskId
    )
    {
        this.mSerialNumber = mSerialNumber;
        this.mAccountId = mAccountId;
        this.mServerId = mServerId;
        this.mActivityId = mActivityId;
        this.mTaskId = mTaskId;
    }

    // getters and setters

    // mSerialNumber

    public String getMSerialNumber()
    {
        return mSerialNumber;
    }


    public void setMSerialNumber(String mSerialNumber)
    {
        this.mSerialNumber = mSerialNumber;
    }

    // mAccountId

    public Integer getMAccountId()
    {
        return mAccountId;
    }


    public void setMAccountId(Integer mAccountId)
    {
        this.mAccountId = mAccountId;
    }

    // mServerId

    public Integer getMServerId()
    {
        return mServerId;
    }


    public void setMServerId(Integer mServerId)
    {
        this.mServerId = mServerId;
    }

    // mActivityId

    public Integer getMActivityId()
    {
        return mActivityId;
    }


    public void setMActivityId(Integer mActivityId)
    {
        this.mActivityId = mActivityId;
    }

    // mTaskId

    public Integer getMTaskId()
    {
        return mTaskId;
    }


    public void setMTaskId(Integer mTaskId)
    {
        this.mTaskId = mTaskId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || this.getClass() != obj.getClass()) {
            return false;
        }
        final Msg_Gm2Logic_Activity_Finsh_Req that = (Msg_Gm2Logic_Activity_Finsh_Req) obj;
        return
                Objects.equals(this.mSerialNumber, that.mSerialNumber) &&
                Objects.equals(this.mAccountId, that.mAccountId) &&
                Objects.equals(this.mServerId, that.mServerId) &&
                Objects.equals(this.mActivityId, that.mActivityId) &&
                Objects.equals(this.mTaskId, that.mTaskId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mSerialNumber, mAccountId, mServerId, mActivityId, mTaskId);
    }

    @Override
    public String toString() {
        return "Msg_Gm2Logic_Activity_Finsh_Req{" +
                    "mSerialNumber=" + mSerialNumber +
                    ", mAccountId=" + mAccountId +
                    ", mServerId=" + mServerId +
                    ", mActivityId=" + mActivityId +
                    ", mTaskId=" + mTaskId +
                '}';
    }
    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<Msg_Gm2Logic_Activity_Finsh_Req> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public Msg_Gm2Logic_Activity_Finsh_Req newMessage()
    {
        return new Msg_Gm2Logic_Activity_Finsh_Req();
    }

    public Class<Msg_Gm2Logic_Activity_Finsh_Req> typeClass()
    {
        return Msg_Gm2Logic_Activity_Finsh_Req.class;
    }

    public String messageName()
    {
        return Msg_Gm2Logic_Activity_Finsh_Req.class.getSimpleName();
    }

    public String messageFullName()
    {
        return Msg_Gm2Logic_Activity_Finsh_Req.class.getName();
    }

    public boolean isInitialized(Msg_Gm2Logic_Activity_Finsh_Req message)
    {
        return 
            message.mSerialNumber != null 
            && message.mAccountId != null 
            && message.mServerId != null 
            && message.mActivityId != null 
            && message.mTaskId != null;
    }

    public void mergeFrom(Input input, Msg_Gm2Logic_Activity_Finsh_Req message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.mSerialNumber = input.readString();
                    break;
                case 2:
                    message.mAccountId = input.readUInt32();
                    break;
                case 3:
                    message.mServerId = input.readUInt32();
                    break;
                case 4:
                    message.mActivityId = input.readUInt32();
                    break;
                case 5:
                    message.mTaskId = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, Msg_Gm2Logic_Activity_Finsh_Req message) throws IOException
    {
        if(message.mSerialNumber == null)
            throw new UninitializedMessageException(message);
        output.writeString(1, message.mSerialNumber, false);

        if(message.mAccountId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(2, message.mAccountId, false);

        if(message.mServerId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(3, message.mServerId, false);

        if(message.mActivityId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(4, message.mActivityId, false);

        if(message.mTaskId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(5, message.mTaskId, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    

}
