// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.account;

import javax.annotation.Generated;

@Generated("java_bean")
public enum AccountRes implements io.protostuff.EnumLite<AccountRes>
{
    AccountRes_Login_AccountError(1),
    AccountRes_Login_KeyError(2),
    AccountRes_Login_Success(3),
    AccountRes_Reg_AccountError(257),
    AccountRes_Reg_Success(258),
    AccountRes_CreatePlayer_ToyNotExists(513),
    AccountRes_CreatePlayer_ToyExists(514),
    AccountRes_ToyActivate_GuidError(769),
    AccountRes_ToyActivate_TypeError(770),
    AccountRes_ToyActivate_OthersBound(771),
    AccountRes_ToyActivate_SelfBound(772),
    AccountRes_ToyActivate_BindError(773),
    AccountRes_ToyActivate_Success(774),
    AccountRes_ToyCheck_GuidError(1025),
    AccountRes_ToyCheck_TypeError(1026),
    AccountRes_ToyCheck_OthersBound(1027),
    AccountRes_ToyCheck_SelfBound(1028),
    AccountRes_ToyCheck_Success(1029);
    
    public final int number;
    
    private AccountRes (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static AccountRes valueOf(int number)
    {
        switch(number) 
        {
            case 1: return AccountRes_Login_AccountError;
            case 2: return AccountRes_Login_KeyError;
            case 3: return AccountRes_Login_Success;
            case 257: return AccountRes_Reg_AccountError;
            case 258: return AccountRes_Reg_Success;
            case 513: return AccountRes_CreatePlayer_ToyNotExists;
            case 514: return AccountRes_CreatePlayer_ToyExists;
            case 769: return AccountRes_ToyActivate_GuidError;
            case 770: return AccountRes_ToyActivate_TypeError;
            case 771: return AccountRes_ToyActivate_OthersBound;
            case 772: return AccountRes_ToyActivate_SelfBound;
            case 773: return AccountRes_ToyActivate_BindError;
            case 774: return AccountRes_ToyActivate_Success;
            case 1025: return AccountRes_ToyCheck_GuidError;
            case 1026: return AccountRes_ToyCheck_TypeError;
            case 1027: return AccountRes_ToyCheck_OthersBound;
            case 1028: return AccountRes_ToyCheck_SelfBound;
            case 1029: return AccountRes_ToyCheck_Success;
            default: return null;
        }
    }
}
