// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.account;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;
import io.protostuff.UninitializedMessageException;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.Objects;

@Generated("java_bean")
public final class Msg_Account2Center_CheckToyActivate_Res implements Externalizable, Message<Msg_Account2Center_CheckToyActivate_Res>, Schema<Msg_Account2Center_CheckToyActivate_Res>
{

    public static Schema<Msg_Account2Center_CheckToyActivate_Res> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static Msg_Account2Center_CheckToyActivate_Res getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final Msg_Account2Center_CheckToyActivate_Res DEFAULT_INSTANCE = new Msg_Account2Center_CheckToyActivate_Res();

    
    private Integer mOperatorAccountId;
    private Integer mOperatorServerId;
    private String mToyGuid;
    private Integer mToyType;
    private Integer mAccountId;
    private Integer mRes;

    public Msg_Account2Center_CheckToyActivate_Res()
    {

    }

    public Msg_Account2Center_CheckToyActivate_Res(
        Integer mOperatorAccountId,
        Integer mOperatorServerId,
        String mToyGuid,
        Integer mToyType,
        Integer mAccountId,
        Integer mRes
    )
    {
        this.mOperatorAccountId = mOperatorAccountId;
        this.mOperatorServerId = mOperatorServerId;
        this.mToyGuid = mToyGuid;
        this.mToyType = mToyType;
        this.mAccountId = mAccountId;
        this.mRes = mRes;
    }

    // getters and setters

    // mOperatorAccountId

    public Integer getMOperatorAccountId()
    {
        return mOperatorAccountId;
    }


    public void setMOperatorAccountId(Integer mOperatorAccountId)
    {
        this.mOperatorAccountId = mOperatorAccountId;
    }

    // mOperatorServerId

    public Integer getMOperatorServerId()
    {
        return mOperatorServerId;
    }


    public void setMOperatorServerId(Integer mOperatorServerId)
    {
        this.mOperatorServerId = mOperatorServerId;
    }

    // mToyGuid

    public String getMToyGuid()
    {
        return mToyGuid;
    }


    public void setMToyGuid(String mToyGuid)
    {
        this.mToyGuid = mToyGuid;
    }

    // mToyType

    public Integer getMToyType()
    {
        return mToyType;
    }


    public void setMToyType(Integer mToyType)
    {
        this.mToyType = mToyType;
    }

    // mAccountId

    public Integer getMAccountId()
    {
        return mAccountId;
    }


    public void setMAccountId(Integer mAccountId)
    {
        this.mAccountId = mAccountId;
    }

    // mRes

    public Integer getMRes()
    {
        return mRes;
    }


    public void setMRes(Integer mRes)
    {
        this.mRes = mRes;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || this.getClass() != obj.getClass()) {
            return false;
        }
        final Msg_Account2Center_CheckToyActivate_Res that = (Msg_Account2Center_CheckToyActivate_Res) obj;
        return
                Objects.equals(this.mOperatorAccountId, that.mOperatorAccountId) &&
                Objects.equals(this.mOperatorServerId, that.mOperatorServerId) &&
                Objects.equals(this.mToyGuid, that.mToyGuid) &&
                Objects.equals(this.mToyType, that.mToyType) &&
                Objects.equals(this.mAccountId, that.mAccountId) &&
                Objects.equals(this.mRes, that.mRes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mOperatorAccountId, mOperatorServerId, mToyGuid, mToyType, mAccountId, mRes);
    }

    @Override
    public String toString() {
        return "Msg_Account2Center_CheckToyActivate_Res{" +
                    "mOperatorAccountId=" + mOperatorAccountId +
                    ", mOperatorServerId=" + mOperatorServerId +
                    ", mToyGuid=" + mToyGuid +
                    ", mToyType=" + mToyType +
                    ", mAccountId=" + mAccountId +
                    ", mRes=" + mRes +
                '}';
    }
    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<Msg_Account2Center_CheckToyActivate_Res> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public Msg_Account2Center_CheckToyActivate_Res newMessage()
    {
        return new Msg_Account2Center_CheckToyActivate_Res();
    }

    public Class<Msg_Account2Center_CheckToyActivate_Res> typeClass()
    {
        return Msg_Account2Center_CheckToyActivate_Res.class;
    }

    public String messageName()
    {
        return Msg_Account2Center_CheckToyActivate_Res.class.getSimpleName();
    }

    public String messageFullName()
    {
        return Msg_Account2Center_CheckToyActivate_Res.class.getName();
    }

    public boolean isInitialized(Msg_Account2Center_CheckToyActivate_Res message)
    {
        return 
            message.mOperatorAccountId != null 
            && message.mOperatorServerId != null 
            && message.mToyGuid != null 
            && message.mToyType != null 
            && message.mAccountId != null 
            && message.mRes != null;
    }

    public void mergeFrom(Input input, Msg_Account2Center_CheckToyActivate_Res message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.mOperatorAccountId = input.readUInt32();
                    break;
                case 2:
                    message.mOperatorServerId = input.readUInt32();
                    break;
                case 3:
                    message.mToyGuid = input.readString();
                    break;
                case 4:
                    message.mToyType = input.readUInt32();
                    break;
                case 5:
                    message.mAccountId = input.readUInt32();
                    break;
                case 6:
                    message.mRes = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, Msg_Account2Center_CheckToyActivate_Res message) throws IOException
    {
        if(message.mOperatorAccountId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(1, message.mOperatorAccountId, false);

        if(message.mOperatorServerId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(2, message.mOperatorServerId, false);

        if(message.mToyGuid == null)
            throw new UninitializedMessageException(message);
        output.writeString(3, message.mToyGuid, false);

        if(message.mToyType == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(4, message.mToyType, false);

        if(message.mAccountId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(5, message.mAccountId, false);

        if(message.mRes == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(6, message.mRes, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    

}
