// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.account;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;
import io.protostuff.UninitializedMessageException;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.Objects;

@Generated("java_bean")
public final class Msg_Center2Account_Reg_Login_Key_Res implements Externalizable, Message<Msg_Center2Account_Reg_Login_Key_Res>, Schema<Msg_Center2Account_Reg_Login_Key_Res>
{

    public static Schema<Msg_Center2Account_Reg_Login_Key_Res> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static Msg_Center2Account_Reg_Login_Key_Res getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final Msg_Center2Account_Reg_Login_Key_Res DEFAULT_INSTANCE = new Msg_Center2Account_Reg_Login_Key_Res();

    
    private String mSerialNumber;
    private Integer mAccountId;
    private Integer mKey;

    public Msg_Center2Account_Reg_Login_Key_Res()
    {

    }

    public Msg_Center2Account_Reg_Login_Key_Res(
        String mSerialNumber,
        Integer mAccountId,
        Integer mKey
    )
    {
        this.mSerialNumber = mSerialNumber;
        this.mAccountId = mAccountId;
        this.mKey = mKey;
    }

    // getters and setters

    // mSerialNumber

    public String getMSerialNumber()
    {
        return mSerialNumber;
    }


    public void setMSerialNumber(String mSerialNumber)
    {
        this.mSerialNumber = mSerialNumber;
    }

    // mAccountId

    public Integer getMAccountId()
    {
        return mAccountId;
    }


    public void setMAccountId(Integer mAccountId)
    {
        this.mAccountId = mAccountId;
    }

    // mKey

    public Integer getMKey()
    {
        return mKey;
    }


    public void setMKey(Integer mKey)
    {
        this.mKey = mKey;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || this.getClass() != obj.getClass()) {
            return false;
        }
        final Msg_Center2Account_Reg_Login_Key_Res that = (Msg_Center2Account_Reg_Login_Key_Res) obj;
        return
                Objects.equals(this.mSerialNumber, that.mSerialNumber) &&
                Objects.equals(this.mAccountId, that.mAccountId) &&
                Objects.equals(this.mKey, that.mKey);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mSerialNumber, mAccountId, mKey);
    }

    @Override
    public String toString() {
        return "Msg_Center2Account_Reg_Login_Key_Res{" +
                    "mSerialNumber=" + mSerialNumber +
                    ", mAccountId=" + mAccountId +
                    ", mKey=" + mKey +
                '}';
    }
    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<Msg_Center2Account_Reg_Login_Key_Res> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public Msg_Center2Account_Reg_Login_Key_Res newMessage()
    {
        return new Msg_Center2Account_Reg_Login_Key_Res();
    }

    public Class<Msg_Center2Account_Reg_Login_Key_Res> typeClass()
    {
        return Msg_Center2Account_Reg_Login_Key_Res.class;
    }

    public String messageName()
    {
        return Msg_Center2Account_Reg_Login_Key_Res.class.getSimpleName();
    }

    public String messageFullName()
    {
        return Msg_Center2Account_Reg_Login_Key_Res.class.getName();
    }

    public boolean isInitialized(Msg_Center2Account_Reg_Login_Key_Res message)
    {
        return 
            message.mSerialNumber != null 
            && message.mAccountId != null 
            && message.mKey != null;
    }

    public void mergeFrom(Input input, Msg_Center2Account_Reg_Login_Key_Res message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.mSerialNumber = input.readString();
                    break;
                case 2:
                    message.mAccountId = input.readUInt32();
                    break;
                case 3:
                    message.mKey = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, Msg_Center2Account_Reg_Login_Key_Res message) throws IOException
    {
        if(message.mSerialNumber == null)
            throw new UninitializedMessageException(message);
        output.writeString(1, message.mSerialNumber, false);

        if(message.mAccountId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(2, message.mAccountId, false);

        if(message.mKey == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(3, message.mKey, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    

}
