// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.account;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;
import io.protostuff.UninitializedMessageException;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.Objects;

@Generated("java_bean")
public final class Msg_Center2Account_ToyActivate_Req implements Externalizable, Message<Msg_Center2Account_ToyActivate_Req>, Schema<Msg_Center2Account_ToyActivate_Req>
{

    public static Schema<Msg_Center2Account_ToyActivate_Req> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static Msg_Center2Account_ToyActivate_Req getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final Msg_Center2Account_ToyActivate_Req DEFAULT_INSTANCE = new Msg_Center2Account_ToyActivate_Req();

    
    private Integer mOperatorAccountId;
    private Integer mOperatorServerId;
    private String mToyGuid;
    private Integer mToyType;
    private String mToyKey;

    public Msg_Center2Account_ToyActivate_Req()
    {

    }

    public Msg_Center2Account_ToyActivate_Req(
        Integer mOperatorAccountId,
        Integer mOperatorServerId,
        String mToyGuid,
        Integer mToyType,
        String mToyKey
    )
    {
        this.mOperatorAccountId = mOperatorAccountId;
        this.mOperatorServerId = mOperatorServerId;
        this.mToyGuid = mToyGuid;
        this.mToyType = mToyType;
        this.mToyKey = mToyKey;
    }

    // getters and setters

    // mOperatorAccountId

    public Integer getMOperatorAccountId()
    {
        return mOperatorAccountId;
    }


    public void setMOperatorAccountId(Integer mOperatorAccountId)
    {
        this.mOperatorAccountId = mOperatorAccountId;
    }

    // mOperatorServerId

    public Integer getMOperatorServerId()
    {
        return mOperatorServerId;
    }


    public void setMOperatorServerId(Integer mOperatorServerId)
    {
        this.mOperatorServerId = mOperatorServerId;
    }

    // mToyGuid

    public String getMToyGuid()
    {
        return mToyGuid;
    }


    public void setMToyGuid(String mToyGuid)
    {
        this.mToyGuid = mToyGuid;
    }

    // mToyType

    public Integer getMToyType()
    {
        return mToyType;
    }


    public void setMToyType(Integer mToyType)
    {
        this.mToyType = mToyType;
    }

    // mToyKey

    public String getMToyKey()
    {
        return mToyKey;
    }


    public void setMToyKey(String mToyKey)
    {
        this.mToyKey = mToyKey;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || this.getClass() != obj.getClass()) {
            return false;
        }
        final Msg_Center2Account_ToyActivate_Req that = (Msg_Center2Account_ToyActivate_Req) obj;
        return
                Objects.equals(this.mOperatorAccountId, that.mOperatorAccountId) &&
                Objects.equals(this.mOperatorServerId, that.mOperatorServerId) &&
                Objects.equals(this.mToyGuid, that.mToyGuid) &&
                Objects.equals(this.mToyType, that.mToyType) &&
                Objects.equals(this.mToyKey, that.mToyKey);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mOperatorAccountId, mOperatorServerId, mToyGuid, mToyType, mToyKey);
    }

    @Override
    public String toString() {
        return "Msg_Center2Account_ToyActivate_Req{" +
                    "mOperatorAccountId=" + mOperatorAccountId +
                    ", mOperatorServerId=" + mOperatorServerId +
                    ", mToyGuid=" + mToyGuid +
                    ", mToyType=" + mToyType +
                    ", mToyKey=" + mToyKey +
                '}';
    }
    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<Msg_Center2Account_ToyActivate_Req> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public Msg_Center2Account_ToyActivate_Req newMessage()
    {
        return new Msg_Center2Account_ToyActivate_Req();
    }

    public Class<Msg_Center2Account_ToyActivate_Req> typeClass()
    {
        return Msg_Center2Account_ToyActivate_Req.class;
    }

    public String messageName()
    {
        return Msg_Center2Account_ToyActivate_Req.class.getSimpleName();
    }

    public String messageFullName()
    {
        return Msg_Center2Account_ToyActivate_Req.class.getName();
    }

    public boolean isInitialized(Msg_Center2Account_ToyActivate_Req message)
    {
        return 
            message.mOperatorAccountId != null 
            && message.mOperatorServerId != null 
            && message.mToyGuid != null 
            && message.mToyType != null 
            && message.mToyKey != null;
    }

    public void mergeFrom(Input input, Msg_Center2Account_ToyActivate_Req message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.mOperatorAccountId = input.readUInt32();
                    break;
                case 2:
                    message.mOperatorServerId = input.readUInt32();
                    break;
                case 3:
                    message.mToyGuid = input.readString();
                    break;
                case 4:
                    message.mToyType = input.readUInt32();
                    break;
                case 5:
                    message.mToyKey = input.readString();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, Msg_Center2Account_ToyActivate_Req message) throws IOException
    {
        if(message.mOperatorAccountId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(1, message.mOperatorAccountId, false);

        if(message.mOperatorServerId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(2, message.mOperatorServerId, false);

        if(message.mToyGuid == null)
            throw new UninitializedMessageException(message);
        output.writeString(3, message.mToyGuid, false);

        if(message.mToyType == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(4, message.mToyType, false);

        if(message.mToyKey == null)
            throw new UninitializedMessageException(message);
        output.writeString(5, message.mToyKey, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    

}
