// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.account;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;
import io.protostuff.UninitializedMessageException;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@Generated("java_bean")
public final class Msg_Account2Center_Create_Player_Res implements Externalizable, Message<Msg_Account2Center_Create_Player_Res>, Schema<Msg_Account2Center_Create_Player_Res>
{

    public static Schema<Msg_Account2Center_Create_Player_Res> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static Msg_Account2Center_Create_Player_Res getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final Msg_Account2Center_Create_Player_Res DEFAULT_INSTANCE = new Msg_Account2Center_Create_Player_Res();

    
    private Integer mOperatorAccountId;
    private Integer mOperatorServerId;
    private String mName;
    private Integer mCreateToyType;
    private List<Integer> mActivateToyType = new ArrayList<>();
    private Integer mRes;

    public Msg_Account2Center_Create_Player_Res()
    {

    }

    public Msg_Account2Center_Create_Player_Res(
        Integer mOperatorAccountId,
        Integer mOperatorServerId,
        String mName,
        Integer mCreateToyType,
        Integer mRes
    )
    {
        this.mOperatorAccountId = mOperatorAccountId;
        this.mOperatorServerId = mOperatorServerId;
        this.mName = mName;
        this.mCreateToyType = mCreateToyType;
        this.mRes = mRes;
    }

    // getters and setters

    // mOperatorAccountId

    public Integer getMOperatorAccountId()
    {
        return mOperatorAccountId;
    }


    public void setMOperatorAccountId(Integer mOperatorAccountId)
    {
        this.mOperatorAccountId = mOperatorAccountId;
    }

    // mOperatorServerId

    public Integer getMOperatorServerId()
    {
        return mOperatorServerId;
    }


    public void setMOperatorServerId(Integer mOperatorServerId)
    {
        this.mOperatorServerId = mOperatorServerId;
    }

    // mName

    public String getMName()
    {
        return mName;
    }


    public void setMName(String mName)
    {
        this.mName = mName;
    }

    // mCreateToyType

    public Integer getMCreateToyType()
    {
        return mCreateToyType;
    }


    public void setMCreateToyType(Integer mCreateToyType)
    {
        this.mCreateToyType = mCreateToyType;
    }

    // mActivateToyType

    public List<Integer> getMActivateToyTypeList()
    {
        return mActivateToyType;
    }


    public void setMActivateToyTypeList(List<Integer> mActivateToyType)
    {
        this.mActivateToyType = mActivateToyType;
    }

    // mRes

    public Integer getMRes()
    {
        return mRes;
    }


    public void setMRes(Integer mRes)
    {
        this.mRes = mRes;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || this.getClass() != obj.getClass()) {
            return false;
        }
        final Msg_Account2Center_Create_Player_Res that = (Msg_Account2Center_Create_Player_Res) obj;
        return
                Objects.equals(this.mOperatorAccountId, that.mOperatorAccountId) &&
                Objects.equals(this.mOperatorServerId, that.mOperatorServerId) &&
                Objects.equals(this.mName, that.mName) &&
                Objects.equals(this.mCreateToyType, that.mCreateToyType) &&
                Objects.equals(this.mActivateToyType, that.mActivateToyType) &&
                Objects.equals(this.mRes, that.mRes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mOperatorAccountId, mOperatorServerId, mName, mCreateToyType, mActivateToyType, mRes);
    }

    @Override
    public String toString() {
        return "Msg_Account2Center_Create_Player_Res{" +
                    "mOperatorAccountId=" + mOperatorAccountId +
                    ", mOperatorServerId=" + mOperatorServerId +
                    ", mName=" + mName +
                    ", mCreateToyType=" + mCreateToyType +
                    ", mActivateToyType=" + mActivateToyType +
                    ", mRes=" + mRes +
                '}';
    }
    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<Msg_Account2Center_Create_Player_Res> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public Msg_Account2Center_Create_Player_Res newMessage()
    {
        return new Msg_Account2Center_Create_Player_Res();
    }

    public Class<Msg_Account2Center_Create_Player_Res> typeClass()
    {
        return Msg_Account2Center_Create_Player_Res.class;
    }

    public String messageName()
    {
        return Msg_Account2Center_Create_Player_Res.class.getSimpleName();
    }

    public String messageFullName()
    {
        return Msg_Account2Center_Create_Player_Res.class.getName();
    }

    public boolean isInitialized(Msg_Account2Center_Create_Player_Res message)
    {
        return 
            message.mOperatorAccountId != null 
            && message.mOperatorServerId != null 
            && message.mName != null 
            && message.mCreateToyType != null 
            && message.mRes != null;
    }

    public void mergeFrom(Input input, Msg_Account2Center_Create_Player_Res message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.mOperatorAccountId = input.readUInt32();
                    break;
                case 2:
                    message.mOperatorServerId = input.readUInt32();
                    break;
                case 3:
                    message.mName = input.readString();
                    break;
                case 4:
                    message.mCreateToyType = input.readUInt32();
                    break;
                case 5:
                    if(message.mActivateToyType == null)
                        message.mActivateToyType = new ArrayList<Integer>();
                    message.mActivateToyType.add(input.readUInt32());break;
                case 6:
                    message.mRes = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, Msg_Account2Center_Create_Player_Res message) throws IOException
    {
        if(message.mOperatorAccountId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(1, message.mOperatorAccountId, false);

        if(message.mOperatorServerId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(2, message.mOperatorServerId, false);

        if(message.mName == null)
            throw new UninitializedMessageException(message);
        output.writeString(3, message.mName, false);

        if(message.mCreateToyType == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(4, message.mCreateToyType, false);

        if(message.mActivateToyType != null)
        {
            for(Integer mActivateToyType : message.mActivateToyType)
            {
                if(mActivateToyType != null)
                    output.writeUInt32(5, mActivateToyType, true);
            }
        }

        if(message.mRes == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(6, message.mRes, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    

}
