// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.account;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;
import io.protostuff.UninitializedMessageException;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.Objects;

@Generated("java_bean")
public final class Msg_Center2Account_Create_Player_Req implements Externalizable, Message<Msg_Center2Account_Create_Player_Req>, Schema<Msg_Center2Account_Create_Player_Req>
{

    public static Schema<Msg_Center2Account_Create_Player_Req> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static Msg_Center2Account_Create_Player_Req getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final Msg_Center2Account_Create_Player_Req DEFAULT_INSTANCE = new Msg_Center2Account_Create_Player_Req();

    
    private Integer mOperatorAccountId;
    private Integer mOperatorServerId;
    private String mName;
    private Integer mCreateToyType;

    public Msg_Center2Account_Create_Player_Req()
    {

    }

    public Msg_Center2Account_Create_Player_Req(
        Integer mOperatorAccountId,
        Integer mOperatorServerId,
        String mName,
        Integer mCreateToyType
    )
    {
        this.mOperatorAccountId = mOperatorAccountId;
        this.mOperatorServerId = mOperatorServerId;
        this.mName = mName;
        this.mCreateToyType = mCreateToyType;
    }

    // getters and setters

    // mOperatorAccountId

    public Integer getMOperatorAccountId()
    {
        return mOperatorAccountId;
    }


    public void setMOperatorAccountId(Integer mOperatorAccountId)
    {
        this.mOperatorAccountId = mOperatorAccountId;
    }

    // mOperatorServerId

    public Integer getMOperatorServerId()
    {
        return mOperatorServerId;
    }


    public void setMOperatorServerId(Integer mOperatorServerId)
    {
        this.mOperatorServerId = mOperatorServerId;
    }

    // mName

    public String getMName()
    {
        return mName;
    }


    public void setMName(String mName)
    {
        this.mName = mName;
    }

    // mCreateToyType

    public Integer getMCreateToyType()
    {
        return mCreateToyType;
    }


    public void setMCreateToyType(Integer mCreateToyType)
    {
        this.mCreateToyType = mCreateToyType;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || this.getClass() != obj.getClass()) {
            return false;
        }
        final Msg_Center2Account_Create_Player_Req that = (Msg_Center2Account_Create_Player_Req) obj;
        return
                Objects.equals(this.mOperatorAccountId, that.mOperatorAccountId) &&
                Objects.equals(this.mOperatorServerId, that.mOperatorServerId) &&
                Objects.equals(this.mName, that.mName) &&
                Objects.equals(this.mCreateToyType, that.mCreateToyType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mOperatorAccountId, mOperatorServerId, mName, mCreateToyType);
    }

    @Override
    public String toString() {
        return "Msg_Center2Account_Create_Player_Req{" +
                    "mOperatorAccountId=" + mOperatorAccountId +
                    ", mOperatorServerId=" + mOperatorServerId +
                    ", mName=" + mName +
                    ", mCreateToyType=" + mCreateToyType +
                '}';
    }
    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<Msg_Center2Account_Create_Player_Req> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public Msg_Center2Account_Create_Player_Req newMessage()
    {
        return new Msg_Center2Account_Create_Player_Req();
    }

    public Class<Msg_Center2Account_Create_Player_Req> typeClass()
    {
        return Msg_Center2Account_Create_Player_Req.class;
    }

    public String messageName()
    {
        return Msg_Center2Account_Create_Player_Req.class.getSimpleName();
    }

    public String messageFullName()
    {
        return Msg_Center2Account_Create_Player_Req.class.getName();
    }

    public boolean isInitialized(Msg_Center2Account_Create_Player_Req message)
    {
        return 
            message.mOperatorAccountId != null 
            && message.mOperatorServerId != null 
            && message.mName != null 
            && message.mCreateToyType != null;
    }

    public void mergeFrom(Input input, Msg_Center2Account_Create_Player_Req message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.mOperatorAccountId = input.readUInt32();
                    break;
                case 2:
                    message.mOperatorServerId = input.readUInt32();
                    break;
                case 3:
                    message.mName = input.readString();
                    break;
                case 4:
                    message.mCreateToyType = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, Msg_Center2Account_Create_Player_Req message) throws IOException
    {
        if(message.mOperatorAccountId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(1, message.mOperatorAccountId, false);

        if(message.mOperatorServerId == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(2, message.mOperatorServerId, false);

        if(message.mName == null)
            throw new UninitializedMessageException(message);
        output.writeString(3, message.mName, false);

        if(message.mCreateToyType == null)
            throw new UninitializedMessageException(message);
        output.writeUInt32(4, message.mCreateToyType, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    

}
