// Generated by the ParseProto.exe  DO NOT EDIT!

package com.fanfandou.platform.serv.game.entity.tol;

import com.fanfandou.platform.api.game.entity.MessageType;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Account2Center_AntiAddiction_Req;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Account2Center_CheckToyActivate_Res;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Account2Center_Create_Player_Res;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Account2Center_Reg_Login_Key_Req;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Account2Center_ToyActivate_Res;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Account2Client_Login_Res;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Account2Client_Reg_Res;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Center2Account_CheckToyActivate_Req;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Center2Account_Create_Player_Req;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Center2Account_Login_Req;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Center2Account_Logout_Req;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Center2Account_Reg_Login_Key_Res;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Center2Account_ToyActivate_Req;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Client2Account_CleanToy_Req;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Client2Account_Login_Req;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_Client2Account_Reg_Req;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_MsgBeginFlag_Account;
import com.fanfandou.platform.serv.game.entity.tol.account.Msg_MsgEndFlag_Account;
import com.fanfandou.platform.serv.game.entity.tol.base.Msg_Broadcast;
import com.fanfandou.platform.serv.game.entity.tol.base.Msg_Connect;
import com.fanfandou.platform.serv.game.entity.tol.base.Msg_Normal;
import com.fanfandou.platform.serv.game.entity.tol.base.Msg_Ping_Req;
import com.fanfandou.platform.serv.game.entity.tol.base.Msg_Ping_Res;
import com.fanfandou.platform.serv.game.entity.tol.base.Msg_Route;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Gm2Logic_Activity_Finsh_Req;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Gm2Logic_Activity_Get_Req;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Gm2Logic_Deposit_Req;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Gm2Logic_GM_Req;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Gm2Logic_Mail_Req;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Gm2Logic_Notice_Req;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Gm2Logic_Route_Req;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Gm2Logic_Shop_Req;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Gm2Logic_TableRefresh_Req;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Logic2Gm_Activity_Finsh_Res;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Logic2Gm_Activity_Get_Res;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Logic2Gm_Deposit_Res;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Logic2Gm_GM_Res;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Logic2Gm_Mail_Res;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Logic2Gm_Notice_Res;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Logic2Gm_Route_Res;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Logic2Gm_Shop_Res;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_Logic2Gm_TableRefresh_Res;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_MsgBeginFlag_GM_Server;
import com.fanfandou.platform.serv.game.entity.tol.gm.Msg_MsgEndFlag_GM_Server;

public enum CommonMsgType {
    MSG_CONNECT(0, Msg_Connect.class),
    MSG_PING_REQ(1, Msg_Ping_Req.class),
    MSG_PING_RES(2, Msg_Ping_Res.class, MessageType.NOT_PROCESS),
    MSG_NORMAL(3, Msg_Normal.class),
    MSG_ROUTE(4, Msg_Route.class),
    MSG_BROADCAST(5, Msg_Broadcast.class),
    MSG_MSGBEGINFLAG_ACCOUNT(1000, Msg_MsgBeginFlag_Account.class),
    MSG_CLIENT2ACCOUNT_LOGIN_REQ(1001, Msg_Client2Account_Login_Req.class),
    MSG_ACCOUNT2CENTER_REG_LOGIN_KEY_REQ(1002, Msg_Account2Center_Reg_Login_Key_Req.class, "mSerialNumber"),
    MSG_CENTER2ACCOUNT_REG_LOGIN_KEY_RES(1003, Msg_Center2Account_Reg_Login_Key_Res.class,
            "mSerialNumber", MessageType.SYNC_PROCESS),
    MSG_ACCOUNT2CLIENT_LOGIN_RES(1004, Msg_Account2Client_Login_Res.class),
    MSG_CLIENT2ACCOUNT_REG_REQ(1005, Msg_Client2Account_Reg_Req.class),
    MSG_ACCOUNT2CLIENT_REG_RES(1006, Msg_Account2Client_Reg_Res.class),
    MSG_CLIENT2ACCOUNT_CLEANTOY_REQ(1007, Msg_Client2Account_CleanToy_Req.class),
    MSG_CENTER2ACCOUNT_CREATE_PLAYER_REQ(1008, Msg_Center2Account_Create_Player_Req.class, MessageType.ASYNC_PROCESS),
    MSG_ACCOUNT2CENTER_CREATE_PLAYER_RES(1009, Msg_Account2Center_Create_Player_Res.class),
    MSG_CENTER2ACCOUNT_TOYACTIVATE_REQ(1010, Msg_Center2Account_ToyActivate_Req.class, MessageType.ASYNC_PROCESS),
    MSG_ACCOUNT2CENTER_TOYACTIVATE_RES(1011, Msg_Account2Center_ToyActivate_Res.class),
    MSG_CENTER2ACCOUNT_CHECKTOYACTIVATE_REQ(1012, Msg_Center2Account_CheckToyActivate_Req.class,
            MessageType.ASYNC_PROCESS),
    MSG_ACCOUNT2CENTER_CHECKTOYACTIVATE_RES(1013, Msg_Account2Center_CheckToyActivate_Res.class),
    MSG_CENTER2ACCOUNT_LOGIN_REQ(1014, Msg_Center2Account_Login_Req.class, MessageType.ASYNC_PROCESS),
    MSG_CENTER2ACCOUNT_LOGOUT_REQ(1015, Msg_Center2Account_Logout_Req.class, MessageType.ASYNC_PROCESS),
    MSG_ACCOUNT2CENTER_ANTIADDICTION_REQ(1016, Msg_Account2Center_AntiAddiction_Req.class),
    MSG_MSGENDFLAG_ACCOUNT(1017, Msg_MsgEndFlag_Account.class),
    MSG_MSGBEGINFLAG_GM_SERVER(2000, Msg_MsgBeginFlag_GM_Server.class),
    MSG_GM2LOGIC_GM_REQ(2001, Msg_Gm2Logic_GM_Req.class, "mSerialNumber"),
    MSG_LOGIC2GM_GM_RES(2002, Msg_Logic2Gm_GM_Res.class, "mSerialNumber", MessageType.SYNC_PROCESS),
    MSG_GM2LOGIC_NOTICE_REQ(2003, Msg_Gm2Logic_Notice_Req.class, "mSerialNumber"),
    MSG_LOGIC2GM_NOTICE_RES(2004, Msg_Logic2Gm_Notice_Res.class, "mSerialNumber", MessageType.ASYNC_PROCESS),
    MSG_GM2LOGIC_TABLEREFRESH_REQ(2005, Msg_Gm2Logic_TableRefresh_Req.class),
    MSG_LOGIC2GM_TABLEREFRESH_RES(2006, Msg_Logic2Gm_TableRefresh_Res.class),
    MSG_GM2LOGIC_DEPOSIT_REQ(2007, Msg_Gm2Logic_Deposit_Req.class, "mSerialNumber"),
    MSG_LOGIC2GM_DEPOSIT_RES(2008, Msg_Logic2Gm_Deposit_Res.class, "mSerialNumber", MessageType.ASYNC_PROCESS),
    MSG_GM2LOGIC_MAIL_REQ(2009, Msg_Gm2Logic_Mail_Req.class, "mSerialNumber"),
    MSG_LOGIC2GM_MAIL_RES(2010, Msg_Logic2Gm_Mail_Res.class, "mSerialNumber", MessageType.ASYNC_PROCESS),
    MSG_GM2LOGIC_SHOP_REQ(2011, Msg_Gm2Logic_Shop_Req.class, "mSerialNumber"),
    MSG_LOGIC2GM_SHOP_RES(2012, Msg_Logic2Gm_Shop_Res.class, "mSerialNumber", MessageType.ASYNC_PROCESS),
    MSG_GM2LOGIC_ROUTE_REQ(2013, Msg_Gm2Logic_Route_Req.class, "mSerialNumber"),
    MSG_LOGIC2GM_ROUTE_RES(2014, Msg_Logic2Gm_Route_Res.class, "mSerialNumber", MessageType.NOT_PROCESS),
    MSG_GM2LOGIC_ACTIVITY_GET_REQ(2015, Msg_Gm2Logic_Activity_Get_Req.class, "mSerialNumber"),
    MSG_LOGIC2GM_ACTIVITY_GET_RES(2016, Msg_Logic2Gm_Activity_Get_Res.class, "mSerialNumber", MessageType.NOT_PROCESS),
    MSG_GM2LOGIC_ACTIVITY_FINSH_REQ(2017, Msg_Gm2Logic_Activity_Finsh_Req.class, "mSerialNumber"),
    MSG_LOGIC2GM_ACTIVITY_FINSH_RES(2018, Msg_Logic2Gm_Activity_Finsh_Res.class, "mSerialNumber", MessageType.NOT_PROCESS),
    MSG_MSGENDFLAG_GM_SERVER(2019, Msg_MsgEndFlag_GM_Server.class);



    private int id;
    private Class clazz;
    //通讯流水号在协议中的字段名，用来反射获取流水号
    private String msgIdFieldName;
    //接收消息的处理类型(仅res消息使用)
    private MessageType msgType;

    CommonMsgType(int id, Class clazz) {
        this.id = id;
        this.clazz = clazz;
    }

    CommonMsgType(int id, Class clazz, String msgIdFieldName) {
        this.id = id;
        this.clazz = clazz;
        this.msgIdFieldName = msgIdFieldName;
    }

    CommonMsgType(int id, Class clazz, String msgIdFieldName, MessageType msgType) {
        this.id = id;
        this.clazz = clazz;
        this.msgIdFieldName = msgIdFieldName;
        this.msgType = msgType;
    }

    CommonMsgType(int id, Class clazz, MessageType msgType) {
        this.id = id;
        this.clazz = clazz;
        this.msgType = msgType;
    }

    public int getId() {
        return id;
    }

    public Class getClazz() {
        return clazz;
    }

    public String getMsgIdFieldName() {
        return msgIdFieldName;
    }

    public MessageType getMsgType() {
        return msgType;
    }

    /**
     * 根据id获取CommonMsgType.
     *
     * @param id id.
     * @return Gender.
     */
    public static CommonMsgType valueOf(int id) {
        CommonMsgType[] types = values();
        for (CommonMsgType type : types) {
            if (type.getId() == id) {
                return type;
            }
        }
        return null;
    }
}
