// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from proto

package com.fanfandou.platform.serv.game.entity.tol.base;

import javax.annotation.Generated;

@Generated("java_bean")
public enum ServerType implements io.protostuff.EnumLite<ServerType>
{
    ServerType_ClientAccount(0),
    ServerType_ClientLogic(1),
    ServerType_ClientChat(2),
    ServerType_ClientBattle(3),
    ServerType_ClientGM(4),
    ServerType_AccountDB(5),
    ServerType_BattleGate(6),
    ServerType_Battle(7),
    ServerType_LogicGate(8),
    ServerType_ChatGate(9),
    ServerType_Logic(10),
    ServerType_PlayerDB(11),
    ServerType_LogDB(12),
    ServerType_Center(13),
    ServerType_Team(14),
    ServerType_Ranking(15),
    ServerType_Union(16),
    ServerType_CenterDB(17);
    
    public final int number;
    
    private ServerType (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static ServerType valueOf(int number)
    {
        switch(number) 
        {
            case 0: return ServerType_ClientAccount;
            case 1: return ServerType_ClientLogic;
            case 2: return ServerType_ClientChat;
            case 3: return ServerType_ClientBattle;
            case 4: return ServerType_ClientGM;
            case 5: return ServerType_AccountDB;
            case 6: return ServerType_BattleGate;
            case 7: return ServerType_Battle;
            case 8: return ServerType_LogicGate;
            case 9: return ServerType_ChatGate;
            case 10: return ServerType_Logic;
            case 11: return ServerType_PlayerDB;
            case 12: return ServerType_LogDB;
            case 13: return ServerType_Center;
            case 14: return ServerType_Team;
            case 15: return ServerType_Ranking;
            case 16: return ServerType_Union;
            case 17: return ServerType_CenterDB;
            default: return null;
        }
    }
}
